"""initial_schema

Revision ID: 74be889dfa97
Revises: 
Create Date: 2026-08-11 03:38:03.429851

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '74be889dfa97'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
