"""add_encrypted_google_api_key

Revision ID: bbfc772b8567
Revises: 74be889dfa97
Create Date: 2026-08-14 02:11:42.636382

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bbfc772b8567'
down_revision: str | Sequence[str] | None = '74be889dfa97'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('encrypted_google_api_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'encrypted_google_api_key')
    # ### end Alembic commands ###
